name 'bootstrap_server'
maintainer 'Myplaceonline'
maintainer_email 'root@myplaceonline.com'
license 'all_rights'
description 'Installs/Configures bootstrap_server'
long_description 'Installs/Configures bootstrap_server'
version '0.1.12'
