name 'bootstrap_server'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures bootstrap_server'
long_description 'Installs/Configures bootstrap_server'
version '0.1.4'
