name 'server_search'
maintainer 'Myplaceonline'
maintainer_email 'root@myplaceonline.com'
license 'all_rights'
description 'Installs/Configures server_search'
long_description 'Installs/Configures server_search'
version '0.1.2'
