name 'server_web'
maintainer 'Myplaceonline'
maintainer_email 'root@myplaceonline.com'
license 'all_rights'
description 'Installs/Configures server_web'
long_description 'Installs/Configures server_web'
version '0.1.111'

depends 'git'
depends 'rvm'
