name 'nfs_server'
maintainer 'Myplaceonline'
maintainer_email 'root@myplaceonline.com'
license 'all_rights'
description 'Installs/Configures nfs_server'
long_description 'Installs/Configures nfs_server'
version '0.1.1'
