name 'server_core'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures server_core'
long_description 'Installs/Configures server_core'
version '0.1.0'
