name 'server_frontend'
maintainer 'Myplaceonline'
maintainer_email 'root@myplaceonline.com'
license 'all_rights'
description 'Installs/Configures server_frontend'
long_description 'Installs/Configures server_frontend'
version '0.1.21'
